/* Generated By:JavaCC: Do not edit this line. JstackParserConstants.java */
package org.basilevs.jstackfilter.grammar.jstack;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JstackParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int QUOTE = 1;
  /** RegularExpression Id. */
  int WORD = 2;
  /** RegularExpression Id. */
  int EOL = 3;
  /** RegularExpression Id. */
  int FRAMEINDENT = 4;
  /** RegularExpression Id. */
  int SPACE = 5;
  /** RegularExpression Id. */
  int TIME = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<QUOTE>",
    "<WORD>",
    "<EOL>",
    "<FRAMEINDENT>",
    "<SPACE>",
    "<TIME>",
    "\"Full thread dump \"",
    "\":\"",
    "\"Threads class SMR info:\"",
    "\"_java_thread_list=\"",
    "\", length=\"",
    "\", elements={\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"$\"",
    "\"<\"",
    "\">\"",
    "\"/\"",
    "\"at \"",
    "\"java.base@\"",
    "\"Native Method\"",
    "\"Unknown Source\"",
    "\"- \"",
    "\"=\"",
    "\"#\"",
    "\"in Object.wait()\"",
    "\"java.lang.Thread.State: \"",
    "\"No compile task\"",
  };

}
