/* Generated By:JavaCC: Do not edit this line. JstackParserConstants.java */
package org.basilevs.jstackfilter.grammar.jstack;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JstackParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 1;
  /** RegularExpression Id. */
  int QUOTE = 2;
  /** RegularExpression Id. */
  int COMMONSYMBOL = 3;
  /** RegularExpression Id. */
  int WORD = 4;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int FRAMEINDENT = 6;
  /** RegularExpression Id. */
  int SPACE = 7;
  /** RegularExpression Id. */
  int TIME = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<COMMENT>",
    "<QUOTE>",
    "<COMMONSYMBOL>",
    "<WORD>",
    "<EOL>",
    "<FRAMEINDENT>",
    "<SPACE>",
    "<TIME>",
    "\"Full thread dump \"",
    "\"Threads class SMR info:\"",
    "\"_java_thread_list=\"",
    "\" length=\"",
    "\" elements={\"",
    "\"}\"",
    "\"at \"",
    "\"- \"",
    "\"=\"",
    "\"#\"",
    "\"java.lang.Thread.State: \"",
    "\"No compile task\"",
  };

}
